### ISSUE TITLE
Stopping worker pool keeps running jobs

### ISSUE THREAD

**Issue by willcodeforfoo** [gocraft/work#24] opened 2016-10-22 23:19 UTC
For some reason, I'm unable to stop a worker pool when there are jobs in the queue. I expected calling `pool.Stop()` to finish up what jobs are being run, and workers to exit while redis holds whatever else is in the queue... but that doesn't seem the case. Below is a small test case that illustrates the problem, mostly adapted from the README:

``` go
package main

import (
    "fmt"
    "github.com/garyburd/redigo/redis"
    "github.com/gocraft/work"
    "time"
)

var redisPool = &redis.Pool{
    MaxActive: 5,
    MaxIdle:   5,
    Wait:      true,
    Dial: func() (redis.Conn, error) {
        return redis.Dial("tcp", ":6379")
    },
}

type Context struct{}

var enqueuer = work.NewEnqueuer("app", redisPool)

func (c *Context) SampleJob(job *work.Job) error {
    fmt.Printf("Sample job %v running\n", job.ID)

    time.Sleep(10 * time.Second)

    fmt.Printf("Sample job %v done\n", job.ID)
    return nil
}

func main() {
    pool := work.NewWorkerPool(Context{}, 2, "app", redisPool)

    pool.Job("sample_job", (*Context).SampleJob)

    for i := 1; i <= 30; i++ {
        enqueuer.Enqueue("sample_job", work.Q{})
    }

    pool.Start()

    time.Sleep(30 * time.Second)
    fmt.Println("30 seconds is up! Stopping workers...")

    pool.Stop()
}
```

Rather than stopping after 30 seconds (plus up to `2 * 10 seconds` for the running jobs to continue) the program continues and workers keep consuming jobs from the queue until it's empty:

```
go run main.go
Sample job 4b6859807fe26e8c344cc302 running
Sample job 6f6f30cd645cd328552983a8 running
Sample job 4b6859807fe26e8c344cc302 done
Sample job 6f6f30cd645cd328552983a8 done
Sample job d17378fcb8ab7e2b42b71ccf running
Sample job 5ad6c131d7faab927db749a2 running
Sample job d17378fcb8ab7e2b42b71ccf done
Sample job 5ad6c131d7faab927db749a2 done
Sample job e7f7e2aaeecf5e16d13ad5bc running
Sample job 5a09255570fabb8813eee575 running
30 seconds is up! Stopping workers...
Sample job 5a09255570fabb8813eee575 done
Sample job e7f7e2aaeecf5e16d13ad5bc done
Sample job f25bcdacb746c94348430143 running
Sample job e399bd4c8d3da1de109310c4 running
Sample job f25bcdacb746c94348430143 done
Sample job e399bd4c8d3da1de109310c4 done
Sample job 27a8ff38c160c64f9a1a52d4 running
Sample job fa0e939272c71d2d927bd032 running
Sample job fa0e939272c71d2d927bd032 done
Sample job 27a8ff38c160c64f9a1a52d4 done
Sample job d189cd37e00f1482aa898550 running
Sample job 40761b0c9f8ecaab192c9b79 running
Sample job d189cd37e00f1482aa898550 done
[...snipped! but this keeps going on for awhile...]
```

Am I doing something wrong in the setup or is this the desired behavior?

**Comment by cypriss** [comment] 2016-10-25 21:58
@willcodeforfoo That's not desired. I think I found the cause of the bug.

Looks like the worker code is stuck in the ```for gotJob``` loop, so we don't process the quit signal until we're done.

Would you like to take a stab at fixing?

**Comment by sohymg** [comment] 2016-11-14 02:14
any update on this? or how to fix the for loop?

**Comment by jalkanen** [comment] 2017-01-03 11:04
Hitting this myself so took a stab at fixing it. PR submitted.

**Comment by yagooar** [comment] 2017-10-22 10:00
Is there any progress on this? I am hitting the same issue.

**Comment by shdunning** [comment] 2017-11-03 20:35
Reviving PR #31

**Comment by shdunning** [comment] 2017-11-03 20:45
Ok, this is fixed in the latest master -- confirmed by running @willcodeforfoo's test code above.

**Closed by shdunning** 2017-11-03 20:45 UTC
